project:
  type: website
  output-dir: .

jupyter: julia-1.9

website:
  title: "TDAmapper"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd

      - section: "Start here"
        contents:
          - index.qmd
      - section: "Tutorials"
        contents:
          - sampling.qmd
      - section: "Guides"
        contents:
          - layout.qmd
      - section: "Fundamentals"
        contents:
          - layout.qmd
      - section: "References"
        contents:
          - layout.qmd


format:
  html:
    theme: cosmos
    css: styles.css
    toc: true



