project:
  type: website
  output-dir: ../docs

jupyter: julia-1.9

website:
  title: "TDAmapper"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd

      - section: "The algorithms"
        contents:
          - mapper.qmd
          - ballmapper.qmd
          - generalization.qmd

      - section: "Examples"
        contents:
          - examples/diabetes.qmd

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true



